/* eslint-disable */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by kvwx

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminSplatRouteImport } from './routes/admin/$'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HistorySplatRouteImport } from './routes/history/$'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as ScheduleSplatRouteImport } from './routes/schedule/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSplatRoute = AdminSplatRouteImport.update({
  id: '/admin/$',
  path: '/admin/$',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HistorySplatRoute = HistorySplatRouteImport.update({
  id: '/history/$',
  path: '/history/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleSplatRoute = ScheduleSplatRouteImport.update({
  id: '/schedule/$',
  path: '/schedule/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin/$': typeof AdminSplatRoute
  '/history': typeof HistoryRoute
  '/history/$': typeof HistorySplatRoute
  '/schedule': typeof ScheduleRoute
  '/schedule/$': typeof ScheduleSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin/$': typeof AdminSplatRoute
  '/history': typeof HistoryRoute
  '/history/$': typeof HistorySplatRoute
  '/schedule': typeof ScheduleRoute
  '/schedule/$': typeof ScheduleSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin/$': typeof AdminSplatRoute
  '/history': typeof HistoryRoute
  '/history/$': typeof HistorySplatRoute
  '/schedule': typeof ScheduleRoute
  '/schedule/$': typeof ScheduleSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/admin/$' | '/history' | '/history/$' | '/schedule' | '/schedule/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/admin/$' | '/history' | '/history/$' | '/schedule' | '/schedule/$'
  id: '__root__' | '/' | '/admin' | '/admin/$' | '/history' | '/history/$' | '/schedule' | '/schedule/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminSplatRoute: typeof AdminSplatRoute
  HistoryRoute: typeof HistoryRoute
  HistorySplatRoute: typeof HistorySplatRoute
  ScheduleRoute: typeof ScheduleRoute
  ScheduleSplatRoute: typeof ScheduleSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': { id: '/'; path: '/'; fullPath: '/'; preLoaderRoute: typeof IndexRouteImport; parentRoute: typeof rootRouteImport }
    '/admin': { id: '/admin'; path: '/admin'; fullPath: '/admin'; preLoaderRoute: typeof AdminRouteImport; parentRoute: typeof rootRouteImport }
    '/admin/$': { id: '/admin/$'; path: '/admin/$'; fullPath: '/admin/$'; preLoaderRoute: typeof AdminSplatRouteImport; parentRoute: typeof rootRouteImport }
    '/history': { id: '/history'; path: '/history'; fullPath: '/history'; preLoaderRoute: typeof HistoryRouteImport; parentRoute: typeof rootRouteImport }
    '/history/$': { id: '/history/$'; path: '/history/$'; fullPath: '/history/$'; preLoaderRoute: typeof HistorySplatRouteImport; parentRoute: typeof rootRouteImport }
    '/schedule': { id: '/schedule'; path: '/schedule'; fullPath: '/schedule'; preLoaderRoute: typeof ScheduleRouteImport; parentRoute: typeof rootRouteImport }
    '/schedule/$': { id: '/schedule/$'; path: '/schedule/$'; fullPath: '/schedule/$'; preLoaderRoute: typeof ScheduleSplatRouteImport; parentRoute: typeof rootRouteImport }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute,
  AdminRoute,
  AdminSplatRoute,
  HistoryRoute,
  HistorySplatRoute,
  ScheduleRoute,
  ScheduleSplatRoute,
}

export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
